### ISSUE TITLE
GUI doesn't startup, but commandline interface is perfect.

### ISSUE THREAD

**Issue by richardfoley** [mauriciojost/olympus-photosync#128]
this is a great little commandline application and saves many a headache easily and sweetly synching photos from the TG-6 down to my PC/laptop over the wifi and without requiring a dumb cable - THANK YOU!

There's a minor issue (minor because the cli does perfectly for me) with the GUI, and I'm only posting the error here fyi. Perhaps there's a simple fix?

```
Caused by: java.lang.ClassNotFoundException: javafx.scene.media.MediaException$Type
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 27 more
```

**Comment by mauriciojost** [comment]
Hi Richard, glad tou find the application useful. About the issue, could you share the app version you are using as well as the java version you have installed? I bet the problem relates to those.
Mauricio

**Comment by richardfoley** [comment]
hi Mauricio,

the app version: `$> olympus-photosync | grep Version
[16:55:04,434 INFO    Starter$] Version: 1.1.0
`

the java version: `$> java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)
`

just FYI, as the CLI works fine :)

**Comment by mauriciojost** [comment]
I reproduced it. I'ts not only your local environment: 
```
With: 
java-11-openjdk-amd64
olympus-photosync-1.1.0

Launching simplly: 
./bin/olympus-photosync --gui

```
the issue can be reproduced.

**Comment by davidcortesortuno** [comment]
Hi, I have the same issue, the `cli` works nicely but the `gui` does not start. I'm using OpenSuse Tumbleweed, my `java` version is 

```
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-suse-2.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.13+8-suse-2.2-x8664, mixed mode)
```

Is there a workaround to the problem?

**Comment by mauriciojost** [comment]
Using a different version of Java, Java 8 for instance. 

For the long term, I am planning (as soon as I get some free time) to provide an embedded JRE to fix this annoying issue. The library used for the UI has changed too much in recent versions of Java, and adapting it all is just too much consuming for me. I prefer to be pragmatic and deliver a more environment-resilient package with JRE embedded. That is what I will use this ticket for.

If you want the workaround: download Java 8 in zip format. Unpack it /opt/somewhere, then 'export PATH=/opt/somewhere/.../bin' and run the application, it will pick up the java version it has been developed for, so the GUI should work correctly.

Best,

Mauricio

**Comment by mauriciojost** [comment]
Embedding JRE is tracked by a different issue. Closing this one.

**Comment by mauriciojost** [comment]
Embedding JRE is tracked by a different issue. Closing this one.
