### ISSUE TITLE
Findings of a Olympus OM D E M10 mark 2 user

### ISSUE THREAD

**Issue by theovandenberg** [mauriciojost/olympus-photosync#19]
Although i have no background in programming it is very inspiring to contribute to this project.
It suits my needs to have a wireless transfer from the camera to the desktop computer.
*The first struggle was to understand where the program should been installed and executed from, it was not really mentioned in the manual. 
*You need the know some basics about making files executable and navigation through your system by the terminal.
All this is sorted out by means of email feedback conversation with the developer and corrected in the manual. The success of this application depends on how easy you can be familiarised to it. For me it suits but i think a front-end might be useful for the Windows platform.
Still in contact with the developer for testing refinements.

**Comment by mauriciojost** [comment]
Hello Theo, thanks for this feedback. I am not trying to help only Linux experienced users but everyone in general, so your feedback is indeed more than welcome.  
Regarding the installation location, I updated README.md (the main documentation) with some examples (like where it could be installed) and instructions to follow to configure and launch the program. I consider it should be now easier to get started. For Linux users I have also provided native packages (`deb` and `rpm`) that should be even easier to install in those OSs. I am now checking how many people are interested in each kind of packaging to go more into that direction.
Regarding the need of using the terminal, it should not be necessary at all. If after using v0.6 you still encounter these practices needed feel free to file a more specific issue.
A front-end requires some development effort, I created an issue #20 regarding this. After that I will see how many people would be interested before proceeding. 
Thanks!
