### ISSUE TITLE
Implement a UI

### ISSUE THREAD

**Issue by mauriciojost** [mauriciojost/olympus-photosync#20]

**Comment by mauriciojost** [comment]
@hercule115 if you feel motivated to implement the GUI, I would surely help you. Are you familiar with Scala?

**Comment by hercule115** [comment]
Unfortunately I am not familiar with Scala. I don't even know if Scala offers GUI support...
I have developed a bunch of applications with GUI using python/wxPython.
First, I will read your code and think about what could be missing in Photosync to implement a nice GUI tool.
I will come back to you of course.
Didier

**Comment by mauriciojost** [comment]
@hercule115 cool! Let me know if I can ease your work somehow (like formatting in a particular way the logs for instance).

**Comment by gvalkov** [comment]
Hi @hercule115 - If you're interested in a similar tool that's written in Python, have a look at [this project](https://github.com/gvalkov/olympus-photosync). In addition to the cli, it has a very basic cross-platform GUI made with tkinter.

**Comment by hercule115** [comment]
Hi, good to know that something already exist in python. I will have a look
at it and tell you.
Unfortunately, not a lot of time available before xmas 😢
Stay tuned

/D

**Comment by mauriciojost** [comment]
Please give this beta version a try please: 

https://bitbucket.org/mauriciojost/olympus-photosync/downloads/photosync-0.10.BETA.GUI.zip

Execute it with the flag: --gui

Also ensure you have java 1.8.40 at least.

It's the very first version (will be marked as beta). I hope it will help get started on the features request :) 

Mauricio

**Comment by hercule115** [comment]
Hi,
I gave it a try.
It runs on High Sierra, with JRE 9.0.1

**Comment by hercule115** [comment]
Some ideas:

- Implement a panel containing the thumbnails of the available pictures
- Implement a contextual menu for each thumbnail : download/delete/info/...
- Some buttons to select/un-select all the thumbnails and download them with globs for selection,
....

**Comment by mauriciojost** [comment]
@hercule115 Nice to hear it worked on MacOS!

Given this, I have created a release 0.11 which is available for download from now on, this release includes the new GUI feature (reminder: to be enabled with --gui flag). Keep in mind it's still in beta. Code coverage is not awesome for instance.

About your above ideas: would you mind creating small issues for each of them? This will let me assign priorities to each of them and tackle one at a time. 

Thanks!

Mauricio

P.S. I am closing this issue. Will work on the more specific GUI issues from now on.
