### ISSUE TITLE
Auto-shutdown

### ISSUE THREAD

**Issue by mariuszlabedzki** [mauriciojost/olympus-photosync#25]
Do you know it is possible to shut down camera via some request over wifi ? Will be sweet if came will shut down when downloading will be completed.

**Comment by mauriciojost** [comment]
Hi @mariuszlabedzki , thanks for the suggestion. This would be an interesting feature, but requires too much development, not suitable for a best-effort mode project. Won't the camera go to sleep after some time? Isn't this time configurable?

**Comment by mariuszlabedzki** [comment]
I cannot see such options - I have canon 600 and in this camera I can configure sleep time, but in olympus tg-4 I dont see any similar feature.

**Comment by mauriciojost** [comment]
Given the interface `photosync` uses to connect to the camera I find this feature difficult to implement. I will leave it open just in case someone has the motivation :)
