### ISSUE TITLE
Enhancement requests in GUI mode...

### ISSUE THREAD

**Issue by hercule115** [mauriciojost/olympus-photosync#52]
Hi 
I tried 0.14 2 on my Macbook air running high Sierra . I used the GUI mode.

It runs well. Very good job . Thank you.

Some enhancements requests:

- The WIFI connection should be checked from the GUI to connect to the camera after having started the application on the PC.
- The engine should exit when using the Quit button from the GUI.
- The thumbnail should not display the text info of the picture as it consumes lot of space on the display. The info are displayed in the bubble (at least on Mac)
- The window should be resizable
- Multiple/non contiguous selection should be available

Very good job!!!

**Comment by mauriciojost** [comment]
Hi @hercule115 

Thanks for the compliments :) 

My thoughts on your suggestions: 
1. I agree, this WIFI connection status should be added to the GUI. It will be addressed in this issue.

2. Could you elaborate more? It looks like a bug. If so, could you please report it in a different issue with more details (and preferably showing the logs too) so I treat it with a different priority? Will not be addressed in the current issue as I lack details and prefer to keep it apart. @hercule115 I count on you to create one issue about this with more details so I can work on it (the close button works correctly on my computer and it's tested on CI builds, so I need to understand better why it happens to you before I can do anything). 
3. You're right, such behaviour should be configurable, I understand that you may be more interested on the image itself than its info at some point in your workflow. This feature will be addressed in this issue. 
4. Yes, I agree on that. Resizeability will be addressed in this issue.
5. This non-contiguous feature is a relatively big one. I will create a new issue for this one. #53

Thanks!

Mauricio

**Comment by mauriciojost** [comment]
An update on the above comments: 
- #49 is fixed
- #56 is fixed
- Show bigger images and smaller comments
- Resizeability.
- #53 to be done.

**Comment by mauriciojost** [comment]
Resizing figured out.

**Comment by mauriciojost** [comment]
Show Bigger images and smaller comments => figured out.

**Comment by mauriciojost** [comment]
Will be available in release `1.0.0`.

**Comment by mauriciojost** [comment]
@hercule115 feel free to test the new version.
