### ISSUE TITLE
Problem with the customisation of output directory in Windows (via _APP_ARGS)

### ISSUE THREAD

**Issue by gilbert-leray** [mauriciojost/olympus-photosync#55]
Hi,

Thank for your software, very helpfull. I use it under Windows 8.1
However, I experienced an issue with the customisation.

When I replace 

```
set _APP_ARGS
``` 
with 
``` 
set _APP_ARGS=Dconfig.file=C:\.....\application.conf
```

running photosync.bat fails :

```
[22:55:20,396 INFO    Starter$] Version: 0.14.0
[22:55:20,496 INFO    Starter$] Loading file configuration: PhotosyncConfig(CameraClientConfig(http,192.168.0.10,80,/DCIM,wlan.*=.*,
(.*),(\d+),(\d+),(\d+),(\d+).*,None),output,Criteria(None,None,None),false,false,false,false)
[22:55:20,497 DEBUG        Os$] Detected OS: Windows (from 'os.name'='windows 8.1')
**Error: Unknown option --Dconfig.file=C:\olympus-photosync-0.14.0\bin\application.conf**
Try --help for more information.
[22:55:20,511 ERROR   Starter$] Application failed

```

Best regards
Gilbert

**Comment by mauriciojost** [comment]
I will try to take a look today.

Mauricio

**Comment by gilbert-leray** [comment]
Thanks, it works fine. But I have a problem to customize the output

I wish to output on a volume that is not the system volume : G:\xxxxx
I got  :

[15:22:19,476 ERROR   Starter$] Application failed
com.typesafe.config.ConfigException$Parse: C:\olympus-photosync-0.14.0\bin\application.conf: 9: Expecting end of input or a comma, g
ot ':' (if you intended ':' to be part of the value for 'output.directory', try enclosing the value in double quotes, or you may be
able to rename the file .properties rather than .conf)

I tried like this : "G:\xxxxx",  doesn't work because of the "\"
(With "G\xxxxx", the files are sync on "C:\xxxxx")

Regards

**Comment by mauriciojost** [comment]
@gilbert-leray could you share the content of application.conf ? I want to reproduce the issue.

**Comment by gilbert-leray** [comment]
# General parameters
###################################################################

# Regular expression used to detect files
file.regex="wlan.*=.*,(.*),(\\d+),(\\d+),(\\d+),(\\d+).*"

# Local directory to be used to download files
output.directory=G:\OlympusSync

# Synchronize only files created strictly between the below dates
# output.fromdate=2017-01-01
# output.untildate=2017-01-03

###################################################################
# Parameters to be used to contact the server (the camera)
###################################################################

# Protocol
server.protocol=http

# Name of the server, or its IP address (used by default)
server.name=192.168.0.10
#server.name=oishare

# Port
server.port=80

# Base URL
server.base.url=/DCIM

# Gui mode enabled
gui=false

# Command line mode enabled
commandline=false

# Dump init file (for customization)
init.config=false

# Shut down camera after sync
shutdownaftersync=false

**Comment by mauriciojost** [comment]
@gilbert-leray from

https://stackoverflow.com/questions/28890426/reading-windows-paths-in-properties-file

you can either do:

```
output.directory=G:\\OlympusSync
```
or
```
output.directory=G:/OlympusSync
```

Could you try and let me know if that works for you?

Mauricio

**Comment by gilbert-leray** [comment]
output.directory=G:\\OlympusSync
output.directory=G:/OlympusSync
both fail because of the ":"

It works with :   output.directory="G:/OlympusSync"

Thanks a lot for your help

Gilbert

**Comment by mauriciojost** [comment]
Good to know!

If you liked the project please star it :) It will motivate me to keep maintaining it.

Best,

Mauricio

**Comment by mauriciojost** [comment]
I will keep this open until I improve the manual.

Mauricio

**Comment by mauriciojost** [comment]
Now the app `--init-config` will show: 
```
[18:53:30,611 INFO    Starter$] File created at: /home/mjost/workspace/olympus-photosync/application.conf
[18:53:30,611 INFO    Starter$] Use it as follows:
[18:53:30,611 INFO    Starter$]   - Under Linux/MacOs execute:
[18:53:30,612 INFO    Starter$]       - photosync -Dconfig.file=/home/mjost/workspace/olympus-photosync/application.conf
[18:53:30,612 INFO    Starter$]   - Under Windows do as follows:
[18:53:30,612 INFO    Starter$]       - Open bin\photosync.bat with a text editor
[18:53:30,612 INFO    Starter$]       - Replace the line:
[18:53:30,612 INFO    Starter$]           set _JAVA_PARAMS=
[18:53:30,612 INFO    Starter$]         with:
[18:53:30,612 INFO    Starter$]           set _JAVA_PARAMS=-Dconfig.file=...
[18:53:30,612 INFO    Starter$]       - Save the file
[18:53:30,612 INFO    Starter$]       - Launch it
```
and the default configuration file will provide more guidance: 
```
# Local directory to be used to download files
# By default write to output directory
output.directory=output
# However in Windows you can use the line below instead:
# output.directory="C:/photosync"
```
Hope this will help other users in the future. 

Closing this issue.

Mauricio

**Comment by gilbert-leray** [comment]
@mauriciojost

There is a little thing you can improve too.
When you quit the GUI after a synchro, the dos window stay open, and you have to close it manualy

Regards.

**Comment by mauriciojost** [comment]
Hi Gilbert!

Thanks for reporting this. I will try to reproduce it in Windows.
Could you please create a new issue with this information so I can treat it
separatly?

Thanks,

Mauricio
