### ISSUE TITLE
The dos window stay open when you quit the GUI

### ISSUE THREAD

**Issue by gilbert-leray** [mauriciojost/olympus-photosync#56]
When you quit the GUI after a synchro, the dos window stay open, and you have to close it manualy

**Comment by hercule115** [comment]
Hi,
Just to mention,
I have the same behavior on my MAC running High Sierra.
/D

Le dim. 11 mars 2018 à 0:07, gilbert-leray <notifications@github.com> a
écrit :

**Comment by mauriciojost** [comment]
So the issue is confirmed. Thanks both for reporting it.

**Comment by mauriciojost** [comment]
I will work on it in the coming days.

**Comment by mauriciojost** [comment]
This issue has been fixed, and will be available in the next release.
