### ISSUE TITLE
Java version check broken with recent openjdk

### ISSUE THREAD

**Issue by xXorAa** [mauriciojost/olympus-photosync#57]
./Modules/binaries/olympus-photosync-0.15.0/bin/olympus-photosync

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .

This is with openjdk 10.

Obviously the internal documentation of the script is also wrong as docs say 1.8+ is required.

**Comment by mauriciojost** [comment]
Will fix. Thanks for the heads up.

**Comment by mauriciojost** [comment]
I am upgrading the packaging plugin version, together with Scala. Let's see if only this fixes the issue.

**Comment by mauriciojost** [comment]
@xXorAa could you please try v0.16.0?
Thanks!

**Comment by mauriciojost** [comment]
Closing.
