### ISSUE TITLE
Config file output.directory format

### ISSUE THREAD

**Issue by cjnaz** [mauriciojost/olympus-photosync#59]
Documentation issue...  When on Windows, the application.conf file `output.directory` setting needs to use forward slashes (not backslashes), and must be in quotes if a drive letter is included.

A working example:
```
output.directory="C:/Users/stuff/Documents/TG-5_pix"
```
On the Windows command line the --output-directory switch uses backslashes and quotes are not needed.

Also note that the README.md 2.c. Configure section refers to `photosync` rather than `olympus-photosync`.

**Comment by mauriciojost** [comment]
Fixed.
